# Lobster workflow: agent-drift-detector
# Monitors agent behavior by comparing recent activity against SOUL.md
#
# Usage:
#   lobster run --file workflow.yaml --args-json '{"soul_path":"/data/clawd/SOUL.md","memory_path":"/data/clawd/memory","days_to_analyze":"7"}'
#
# Requires: jq, find, head
# Note: The LLM analysis step is a placeholder - data collection works

name: agent-drift-detector
description: Compare agent's recent behavior against SOUL.md to detect personality/goal drift

args:
  soul_path:
    description: "Path to agent's SOUL.md or identity file"
    default: "/data/clawd/SOUL.md"
  memory_path:
    description: "Path to recent memory/logs to analyze"
    default: "/data/clawd/memory"
  days_to_analyze:
    description: "How many days of behavior to compare"
    default: "7"
  drift_threshold:
    description: "Alert if drift score exceeds this (0-100)"
    default: "30"

steps:
  - id: read-soul
    command: |
      if [ -f "${soul_path}" ]; then
        cat "${soul_path}"
      else
        echo "SOUL.md not found at ${soul_path}"
      fi

  - id: find-recent-memories
    command: |
      if [ -d "${memory_path}" ]; then
        find "${memory_path}" -name "*.md" -type f -mtime -${days_to_analyze} | sort -r | head -20
      else
        echo ""
      fi

  - id: aggregate-behavior
    stdin: $find-recent-memories.stdout
    command: |
      cat > /tmp/lb_memory_files.txt
      tmpf=$(mktemp)
      while read f; do
        [ -n "$f" ] && [ -f "$f" ] && echo "--- FILE: $f ---" >> "$tmpf" && cat "$f" >> "$tmpf" && echo "" >> "$tmpf"
      done < /tmp/lb_memory_files.txt
      head -c 15000 "$tmpf"
      rm -f "$tmpf" /tmp/lb_memory_files.txt

  - id: prepare-analysis-data
    command: |
      soul_content=$(cat "${soul_path}" 2>/dev/null | head -c 5000 | jq -Rs .)
      behavior_sample=$stdin
      jq -n \
        --arg soul "$soul_content" \
        --arg behavior "$(cat /dev/stdin)" \
        --arg threshold "${drift_threshold}" \
        --arg analyzed_at "$(date -Iseconds)" \
        '{soul_sample: $soul[:500], behavior_length: ($behavior | length), threshold: $threshold, analyzed_at: $analyzed_at, note: "Data collected - LLM analysis step not implemented in shell"}'
    stdin: $aggregate-behavior.stdout

  - id: report
    stdin: $prepare-analysis-data.stdout
    command: |
      jq -r '
        "🔄 Agent Drift Detector",
        "",
        "SOUL.md: \(.soul_sample)...(truncated)",
        "",
        "Behavior data collected: \(.behavior_length) chars from last '${days_to_analyze}' days",
        "Drift threshold: \(.threshold)/100",
        "",
        "⏳ Note: This workflow collects the data.",
        "   LLM comparison analysis would go here:",
        "   - Compare SOUL.md values with recent behavior",
        "   - Score drift from 0-100",
        "   - Identify tone shifts, value drift, capability creep"
      '
