# Lobster workflow: learning-digest
# Searches for educational content based on specified topics
#
# Usage:
#   lobster run --file workflow.yaml --args-json '{"topics":"AI/ML, system design, leadership"}'
#
# Requires: jq, curl
#
# LLM: Uses prompt step for content curation and digest generation

name: learning-digest
description: Curate educational content based on your interests and learning goals

args:
  topics:
    description: "Comma-separated topics to learn about"
    default: "AI/ML, system design, leadership"
  max_items:
    description: "Maximum items per digest"
    default: "10"
  difficulty:
    description: "beginner, intermediate, or advanced"
    default: "intermediate"

steps:
  - id: search-hn-learning
    command: |
      # Search HN Algolia for educational content on each topic
      echo '[]' > /tmp/lb_learn_all.json
      IFS=','
      for topic in ${topics}; do
        topic=$(echo "$topic" | xargs)
        [ -z "$topic" ] && continue
        query=$(echo "${topic} tutorial OR guide OR explained" | jq -sRr @uri)
        curl -sf "https://hn.algolia.com/api/v1/search_by_date?query=${query}&tags=story&hitsPerPage=5" \
          | jq -c --arg t "$topic" '[.hits[]? | {title:.title, url:(.url // "https://news.ycombinator.com/item?id=\(.objectID)"), topic:$t, points:(.points // 0), source:"HN"}]' \
          > /tmp/lb_learn_chunk.json 2>/dev/null || echo '[]' > /tmp/lb_learn_chunk.json
        jq -sc '.[0] + .[1]' /tmp/lb_learn_all.json /tmp/lb_learn_chunk.json > /tmp/lb_learn_merged.json
        mv /tmp/lb_learn_merged.json /tmp/lb_learn_all.json
      done
      cat /tmp/lb_learn_all.json
      rm -f /tmp/lb_learn_all.json /tmp/lb_learn_chunk.json

  - id: search-web-learning
    command: |
      # Use Brave Search if available for broader coverage
      if [ -z "$BRAVE_API_KEY" ]; then
        echo '[]'
        exit 0
      fi
      echo '[]' > /tmp/lb_learn_web.json
      IFS=','
      for topic in ${topics}; do
        topic=$(echo "$topic" | xargs)
        [ -z "$topic" ] && continue
        query=$(echo "${topic} tutorial guide ${difficulty}" | jq -sRr @uri)
        curl -sf "https://api.search.brave.com/res/v1/web/search?q=${query}&count=5&freshness=pw" \
          -H "Accept: application/json" \
          -H "X-Subscription-Token: $BRAVE_API_KEY" \
          | jq -c --arg t "$topic" '[.web.results[]? | {title:.title, url:.url, topic:$t, points:0, source:"Web"}]' \
          > /tmp/lb_learn_wchunk.json 2>/dev/null || echo '[]' > /tmp/lb_learn_wchunk.json
        jq -sc '.[0] + .[1]' /tmp/lb_learn_web.json /tmp/lb_learn_wchunk.json > /tmp/lb_learn_wmerged.json
        mv /tmp/lb_learn_wmerged.json /tmp/lb_learn_web.json
      done
      cat /tmp/lb_learn_web.json
      rm -f /tmp/lb_learn_web.json /tmp/lb_learn_wchunk.json

  - id: combine-and-rank
    command: |
      hn='$search-hn-learning.stdout'
      web='$search-web-learning.stdout'
      echo "$hn" > /tmp/lb_learn_hn.json
      echo "$web" > /tmp/lb_learn_web2.json
      max=${max_items}
      jq -sc --argjson max "$max" '
        .[0] + .[1] |
        unique_by(.url) |
        sort_by(-.points) |
        .[0:$max]
      ' /tmp/lb_learn_hn.json /tmp/lb_learn_web2.json
      rm -f /tmp/lb_learn_hn.json /tmp/lb_learn_web2.json

  - id: curate-digest
    stdin: $combine-and-rank.stdout
    prompt: |
      Curate a learning digest from the resources below.

      Topics of interest: ${topics}
      Target difficulty: ${difficulty}

      For each resource:
      1. Rate quality and relevance (skip low-quality or off-topic items)
      2. Tag difficulty level (beginner/intermediate/advanced)
      3. Estimate reading time
      4. Write a 1-2 sentence summary of what you'll learn

      Group by topic, order by quality. Include a "Start Here" recommendation
      for the single best resource to read first.

      Format as a clean, motivating digest with emoji headers.
    system: >
      You are a learning curator. Select the best resources and make learning paths clear and motivating.

