# Lobster workflow: seo-gap-assassin
# Analyze competitors' content vs yours, find topic gaps, produce structured briefs.
#
# Usage:
#   lobster run --file workflow.yaml --args-json '{"your_domain":"example.com","competitors":"competitor1.com,competitor2.com"}'
#
# Requires: curl, jq, bash
#
# NOTE: Without Ahrefs/SEMrush APIs, we use Brave Search to discover what
# pages/topics each domain covers, then compare to find gaps.

name: seo-gap-assassin
description: >
  Analyze competitors, find content topics they cover that you don't,
  and generate structured content gap reports.

args:
  your_domain:
    description: "Your domain (e.g. example.com)"
  competitors:
    description: "Comma-separated competitor domains (e.g. comp1.com,comp2.com)"
  top_gaps_count:
    description: "Number of top gaps to report"
    default: "20"

steps:
  # Step 1: Discover your domain's indexed pages/topics via Brave Search
  - id: your-pages
    command: |
      domain="${your_domain}"
      tmpout=$(mktemp)
      echo '[]' > "$tmpout"

      # Search for site pages across a few queries
      for offset in 0 10; do
        curl -sf "https://api.search.brave.com/res/v1/web/search?q=site%3A${domain}&count=10&offset=${offset}" \
          -H "Accept: application/json" \
          -H "X-Subscription-Token: ${BRAVE_API_KEY}" \
          > /tmp/lb_seo_your_raw.json 2>/dev/null || echo '{"web":{"results":[]}}' > /tmp/lb_seo_your_raw.json

        jq -c '[.web.results[] // empty | {
          title: .title,
          url: .url,
          description: (.description // "")
        }]' /tmp/lb_seo_your_raw.json > /tmp/lb_seo_your_batch.json 2>/dev/null || echo '[]' > /tmp/lb_seo_your_batch.json

        jq -sc '.[0] + .[1]' "$tmpout" /tmp/lb_seo_your_batch.json > /tmp/lb_seo_your_merged.json
        mv /tmp/lb_seo_your_merged.json "$tmpout"
        sleep 1
      done

      cat "$tmpout"
      rm -f "$tmpout" /tmp/lb_seo_your_raw.json /tmp/lb_seo_your_batch.json

  # Step 2: Discover competitor pages/topics via Brave Search
  - id: competitor-pages
    command: |
      tmpout=$(mktemp)
      echo '[]' > "$tmpout"

      for comp in $(echo "${competitors}" | tr ',' '\n'); do
        comp=$(echo "$comp" | xargs)
        [ -z "$comp" ] && continue

        for offset in 0 10; do
          curl -sf "https://api.search.brave.com/res/v1/web/search?q=site%3A${comp}&count=10&offset=${offset}" \
            -H "Accept: application/json" \
            -H "X-Subscription-Token: ${BRAVE_API_KEY}" \
            > /tmp/lb_seo_comp_raw.json 2>/dev/null || echo '{"web":{"results":[]}}' > /tmp/lb_seo_comp_raw.json

          jq -c --arg comp "$comp" '[.web.results[] // empty | {
            competitor: $comp,
            title: .title,
            url: .url,
            description: (.description // "")
          }]' /tmp/lb_seo_comp_raw.json > /tmp/lb_seo_comp_batch.json 2>/dev/null || echo '[]' > /tmp/lb_seo_comp_batch.json

          jq -sc '.[0] + .[1]' "$tmpout" /tmp/lb_seo_comp_batch.json > /tmp/lb_seo_comp_merged.json
          mv /tmp/lb_seo_comp_merged.json "$tmpout"
          sleep 1
        done
      done

      cat "$tmpout"
      rm -f "$tmpout" /tmp/lb_seo_comp_raw.json /tmp/lb_seo_comp_batch.json

  # Step 3: Save your-pages to temp file for use in gap analysis
  - id: save-your-pages
    stdin: $your-pages.stdout
    command: |
      cat > /tmp/lb_seo_gap_your.json
      echo '{"saved":true}'

  # Step 4: Find content gaps — competitor pages/titles not covered by your domain
  - id: find-gaps
    stdin: $competitor-pages.stdout
    command: |
      cat > /tmp/lb_seo_gap_comp.json

      # Extract your title words as a "coverage" set
      your_words=$(jq -r '
        [.[] | .title // ""] | map(
          gsub("[^a-zA-Z0-9 ]"; " ") | ascii_downcase | split(" ") | map(select(length > 3))
        ) | flatten | unique | join(",")
      ' /tmp/lb_seo_gap_your.json 2>/dev/null || echo "")

      top_n="${top_gaps_count}"

      # Find competitor pages whose title words have low overlap with yours
      jq -c --arg your_words "$your_words" --arg your_domain "${your_domain}" --argjson top_n "$top_n" '
        ($your_words | split(",") | map(select(length > 0)) | map({(.): true}) | add // {}) as $yours |
        [.[] | 
          ((.title // "") | gsub("[^a-zA-Z0-9 ]"; " ") | ascii_downcase | split(" ") | map(select(length > 3))) as $words |
          ($words | map(select($yours[.] == true)) | length) as $overlap |
          ($words | length) as $total |
          select($total > 0) |
          . + {
            overlap_pct: (if $total > 0 then ($overlap * 100 / $total) else 100 end),
            unique_words: [$words[] | select($yours[.] != true)]
          } |
          select(.overlap_pct < 40)
        ] |
        sort_by(.overlap_pct) |
        .[0:$top_n] |
        {
          gap_count: length,
          your_domain: $your_domain,
          gaps: [.[] | {
            competitor: .competitor,
            title: .title,
            url: .url,
            description: .description,
            overlap_pct: .overlap_pct,
            unique_topics: (.unique_words | unique | .[0:10])
          }]
        }
      ' /tmp/lb_seo_gap_comp.json
      rm -f /tmp/lb_seo_gap_comp.json /tmp/lb_seo_gap_your.json

  # Step 5: Generate structured gap data for each content gap
  - id: briefs
    stdin: $find-gaps.stdout
    command: |
      cat > /tmp/lb_seo_gaps.json
      jq -c '
        .gaps as $gaps |
        {
          gap_count: .gap_count,
          your_domain: .your_domain,
          briefs: [
            $gaps[] | {
              target_topic: .title,
              competitor: .competitor,
              competitor_url: .url,
              competitor_description: .description,
              suggested_keywords: .unique_topics,
              overlap_pct: .overlap_pct,
              action: "Create content covering this topic to close the gap"
            }
          ]
        }
      ' /tmp/lb_seo_gaps.json
      rm -f /tmp/lb_seo_gaps.json

  # Step 5b: Use LLM to expand gap data into full content briefs
  - id: llm_briefs
    stdin: $briefs.stdout
    command: |
      cat > /tmp/lb_seo_llm_input.json
      DATA=$(cat /tmp/lb_seo_llm_input.json)
      llm_task.invoke <<PROMPT
      You are an SEO content strategist. Given these content gaps between ${your_domain} and its competitors:

      $DATA

      For each gap (top 5 max), generate a full content brief:
      - target_title: SEO-optimized title
      - search_intent: informational/commercial/transactional
      - recommended_format: blog post/guide/comparison/tutorial
      - outline: array of H2/H3 headings
      - unique_angle: what makes this different from the competitor's version
      - estimated_word_count: number
      - priority: HIGH/MEDIUM/LOW based on gap score and keyword value

      Return JSON: { "content_briefs": [...] }
      PROMPT
      rm -f /tmp/lb_seo_llm_input.json
    env:
      CLAWD_URL: "http://localhost:1691"

  # Step 6: Summary report with AI-generated content briefs
  - id: report
    stdin: $llm_briefs.stdout
    command: |
      jq -r '
        "🎯 **SEO Gap Analysis Complete**\n\n" +
        if (.content_briefs | length) == 0 then
          "No significant gaps found — your content covers competitor topics well!"
        else
          "**AI-Generated Content Briefs:**\n\n" +
          ([.content_briefs[:5][] |
            "### \(.priority // "—") | \(.target_title)\n" +
            "  Intent: \(.search_intent) | Format: \(.recommended_format)\n" +
            "  Word count: ~\(.estimated_word_count)\n" +
            "  Unique angle: \(.unique_angle)\n" +
            "  Outline:\n" +
            ([.outline[]? | "    - " + .] | join("\n"))
          ] | join("\n\n"))
        end
      '
