# Lobster workflow: expense-categorizer
# Read expenses, categorize by keyword matching, and summarize.
#
# Usage:
#   lobster run --file workflow.yaml --args-json '{"expenses_file":"/path/to/expenses.json"}'
#
# Expenses file format (JSON array):
#   [{"date":"2026-01-15","description":"Uber ride downtown","amount":24.50},...]
#
# Requires: jq

name: expense-categorizer
description: Auto-categorize expenses by keyword matching and generate summary

args:
  expenses_file:
    description: "Path to JSON file with expenses [{date, description, amount}]"
  rules_file:
    description: "Optional path to custom categorization rules JSON"
    default: ""

steps:
  - id: load-expenses
    command: |
      if [ ! -f "${expenses_file}" ]; then
        echo '{"error":"Expenses file not found: ${expenses_file}"}' >&2
        echo '[]'
        exit 1
      fi
      cat "${expenses_file}"

  - id: categorize
    stdin: $load-expenses.stdout
    command: |
      cat > /tmp/lb_expenses.json
      # Built-in categorization rules (keyword â†’ category)
      cat > /tmp/lb_cat_rules.json << 'RULES'
      {
        "transport": ["uber","lyft","taxi","gas","fuel","parking","transit","subway","metro","train","flight","airline","delta","united","southwest"],
        "food": ["restaurant","cafe","coffee","starbucks","mcdonald","pizza","grubhub","doordash","ubereats","grocery","supermarket","whole foods","trader joe","safeway","kroger"],
        "utilities": ["electric","water","gas bill","internet","comcast","verizon","att","tmobile","phone bill","utility"],
        "entertainment": ["netflix","spotify","hulu","disney","cinema","movie","concert","game","steam","playstation","xbox","apple tv"],
        "shopping": ["amazon","walmart","target","ebay","etsy","clothing","shoes","electronics","best buy","costco"],
        "health": ["pharmacy","cvs","walgreens","doctor","hospital","dental","gym","fitness","health","medical","insurance"],
        "housing": ["rent","mortgage","maintenance","repair","furniture","ikea","home depot","plumber","electrician"],
        "education": ["book","course","udemy","coursera","tuition","school","university","training"],
        "subscription": ["subscription","membership","annual fee","monthly fee","premium"]
      }
      RULES
      jq -c --slurpfile rules /tmp/lb_cat_rules.json '
        ($rules[0]) as $cat_rules |
        [.[] |
          (.description | ascii_downcase) as $desc |
          ([$cat_rules | to_entries[] |
            select(.value | any(. as $kw | $desc | contains($kw)))
          ] | if length > 0 then .[0].key else "uncategorized" end) as $category |
          . + {category: $category}
        ] |
        {
          categorized: .,
          summary: (group_by(.category) | map({
            category: .[0].category,
            count: length,
            total: (map(.amount) | add | . * 100 | round / 100),
            avg: (map(.amount) | (add / length) | . * 100 | round / 100)
          }) | sort_by(-.total)),
          total: (map(.amount) | add | . * 100 | round / 100),
          count: length,
          uncategorized: ([.[] | select(.category == "uncategorized")] | length)
        }
      ' /tmp/lb_expenses.json
      rm -f /tmp/lb_expenses.json /tmp/lb_cat_rules.json

  - id: llm_recategorize
    stdin: $categorize.stdout
    command: |
      cat > /tmp/ec_llm_input.json
      DATA=$(cat /tmp/ec_llm_input.json)
      llm_task.invoke <<PROMPT
      You are a financial categorization expert. Review these categorized expenses:

      $DATA

      Tasks:
      1. Recategorize any "uncategorized" expenses into the best category
      2. Flag potential duplicate transactions
      3. Flag any suspicious/unusual amounts
      Return the corrected data in the same JSON format with additions: llm_category (for recategorized items), flags (array of {expense_index, flag_type, reason})
      PROMPT
      rm -f /tmp/ec_llm_input.json
    env:
      CLAWD_URL: "http://localhost:1691"

  - id: report
    stdin: $llm_recategorize.stdout
    command: |
      cat > /tmp/lb_cat_report.json
      jq -r '
        "ðŸ·ï¸  Expense Categorizer Report (LLM-Enhanced)\n" +
        "==============================================\n\n" +
        "ðŸ“Š \(.count) expenses totaling $\(.total)\n" +
        (if .uncategorized > 0 then
          "âš ï¸  \(.uncategorized) still uncategorized expense(s)\n"
        else
          "âœ… All expenses categorized!\n"
        end) +
        (if (.categorized | map(select(.llm_category)) | length) > 0 then
          "ðŸ¤– LLM recategorized \(.categorized | map(select(.llm_category)) | length) expense(s)\n"
        else "" end) +
        (if (.flags // [] | length) > 0 then
          "ðŸš© \(.flags | length) flag(s) raised\n"
        else "" end) +
        "\n--- By Category ---\n" +
        (.summary | map(
          "  \(.category): $\(.total) (\(.count) txns, avg $\(.avg))"
        ) | join("\n")) +
        (if (.categorized | map(select(.llm_category)) | length) > 0 then
          "\n\n--- LLM Recategorized ---\n" +
          (.categorized | to_entries | map(select(.value.llm_category)) | map(
            "  #\(.key) \(.value.description): \(.value.category) â†’ \(.value.llm_category)"
          ) | join("\n"))
        else "" end) +
        (if (.flags // [] | length) > 0 then
          "\n\n--- Flags ---\n" +
          (.flags | map(
            "  ðŸš© [\(.flag_type)] expense #\(.expense_index): \(.reason)"
          ) | join("\n"))
        else "" end) +
        "\n\n--- Recent Expenses ---\n" +
        (.categorized | sort_by(.date) | reverse | .[0:10] | map(
          "  [\(.llm_category // .category)] \(.date) \(.description): $\(.amount)"
        ) | join("\n"))
      ' /tmp/lb_cat_report.json
      rm -f /tmp/lb_cat_report.json
