# Lobster workflow: competitor-shadow
# Monitor competitor web pages for changes to pricing, blog, changelog, careers
#
# Usage:
#   lobster run --file workflow.yaml --args-json '{"competitor_url":"https://example.com","competitor_name":"Example"}'
#
# Requires: curl, jq, md5sum/sha256sum

name: competitor-shadow
description: Monitor competitors for changes to pricing, features, blog posts, job listings. Get alerts on any update.

args:
  competitor_url:
    description: "Main competitor website URL (no trailing slash)"
  competitor_name:
    description: "Competitor name for alerts"
    default: "Competitor"
  pages:
    description: "Comma-separated page paths to monitor"
    default: "/pricing,/changelog,/blog,/careers"
  state_file:
    description: "File to store page hashes"
    default: "/tmp/clawflows-competitor-shadow-state.json"

steps:
  - id: load-state
    command: cat "${state_file}" 2>/dev/null || echo '{}'

  - id: check-pages
    command: |
      state_json='$load-state.stdout'
      base_url="${competitor_url}"
      tmpout=$(mktemp)
      echo '[]' > "$tmpout"

      for path in $(echo "${pages}" | tr ',' ' '); do
        path=$(echo "$path" | xargs)
        [ -z "$path" ] && continue
        full_url="${base_url}${path}"

        # Fetch page content (text only, strip tags for comparison)
        content=$(curl -sfL --max-time 15 "$full_url" 2>/dev/null | sed 's/<[^>]*>//g' | tr -s '[:space:]' ' ' | head -c 50000)
        new_hash=$(echo "$content" | sha256sum | cut -d' ' -f1)

        # Get old hash from state
        old_hash=$(echo "$state_json" | jq -r --arg p "$path" '.[$p] // "none"' 2>/dev/null)

        if [ "$old_hash" != "none" ] && [ "$new_hash" != "$old_hash" ]; then
          # Change detected
          jq -c --arg p "$path" --arg u "$full_url" --arg h "$new_hash" \
            '. + [{path:$p, url:$u, hash:$h, changed:true}]' "$tmpout" > /tmp/lb_cs_m.json
          mv /tmp/lb_cs_m.json "$tmpout"
        fi

        # Always update state
        echo "$state_json" | jq --arg p "$path" --arg h "$new_hash" '. + {($p):$h}' > /tmp/lb_cs_state.json
        state_json=$(cat /tmp/lb_cs_state.json)
      done

      # Write updated state
      echo "$state_json" > "${state_file}"

      cat "$tmpout"
      rm -f "$tmpout" /tmp/lb_cs_m.json /tmp/lb_cs_state.json

  - id: analyze-changes
    command: |
      llm_task.invoke --prompt "SYSTEM: You are a competitive intelligence analyst. Focus on strategic implications, not just describing changes. Be direct and actionable.\n\nUSER: Analyze these competitor page changes for ${competitor_name}. For each changed page, explain what likely changed and why it matters. If careers/jobs pages changed, analyze hiring signals (what roles, what teams are growing, what it implies about their strategy). If pricing changed, flag it as high priority. If no changes detected (empty array), say so briefly. Keep the analysis concise and actionable.\n\nDATA:\n$(cat /dev/stdin)"
    stdin: $check-pages.stdout
    env:
      CLAWD_URL: "http://127.0.0.1:3000"
    condition: true
