# Lobster workflow: standup-notes
# Reads yesterday's memory file and generates standup notes
#
# Usage:
#   lobster run --file workflow.yaml --args-json '{"memory_path":"/data/clawd/memory"}'
#
# Requires: jq, date
# LLM: Uses prompt step (llm:host by default — uses your agent's model)

name: standup-notes
description: Auto-generate daily standup notes from yesterday's activity

args:
  memory_path:
    description: "Path to agent memory directory"
    default: "/data/clawd/memory"
  include_blockers:
    description: "Include blockers section (true/false)"
    default: "true"

steps:
  - id: read-yesterday
    command: |
      yesterday=$(date -d "yesterday" +%Y-%m-%d 2>/dev/null || date -v-1d +%Y-%m-%d)
      file="${memory_path}/${yesterday}.md"
      echo "$yesterday" > /tmp/lb_standup_date.txt
      if [ -f "$file" ]; then
        cp "$file" /tmp/lb_standup_yesterday.md
        echo "found"
      else
        echo "(No memory file found for ${yesterday})" > /tmp/lb_standup_yesterday.md
        echo "empty"
      fi

  - id: get-calendar
    command: |
      if [ -x /data/clawd/.venv-gcal/bin/gcalcli ]; then
        TZ=Asia/Jerusalem /data/clawd/.venv-gcal/bin/gcalcli agenda --nocolor --nostarted 2>/dev/null > /tmp/lb_standup_cal.txt || echo "(calendar unavailable)" > /tmp/lb_standup_cal.txt
      else
        echo "(gcalcli not available)" > /tmp/lb_standup_cal.txt
      fi
      echo "done"

  - id: collect-context
    command: |
      yesterday_date=$(cat /tmp/lb_standup_date.txt)
      echo "=== Yesterday's Activity (${yesterday_date}) ==="
      cat /tmp/lb_standup_yesterday.md
      echo ""
      echo "=== Today's Calendar ==="
      cat /tmp/lb_standup_cal.txt
      rm -f /tmp/lb_standup_date.txt /tmp/lb_standup_yesterday.md /tmp/lb_standup_cal.txt

  - id: generate-standup
    stdin: $collect-context.stdout
    prompt: |
      Generate a daily standup update from the activity log and calendar below.

      Structure it as:
      - **Yesterday:** What was accomplished (extract key items from the activity log)
      - **Today:** What's planned (based on calendar + any carry-over items)
      - **Blockers:** Any identified blockers (or "None" if clear)

      Keep it concise. Use bullet points. Include emoji for readability.
      If the activity log is sparse, note that and suggest reviewing manually.
    system: >
      You are a standup note generator. Extract concrete accomplishments and
      plans from raw activity logs. Be specific about what was done, not vague.
      Keep each bullet to one line.
